#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi

source "$ROOT/_localsettings"

if [ "X$LIGHTS" != "X" ]; then
	LOCAL_LIGHTS="$LIGHTS"
fi

function get_now_time {
	DATE=$(date +%r | sed 's/^[ ]//g') #trim whitespace to support diff vers of date cmd
	echo $(echo $DATE | cut -d ":" -f 1,2) $(echo $DATE | cut -d " " -f 2)
}

function get_time_val {
	declare -i OFFSET=0
	if [ -n "$2" ]; then
		OFFSET=$2*60
	fi
	SUPPORTS_J=`date -j 2>/dev/null`
	if [ "X$SUPPORTS_J" == "X" ]; then
		DATE=`date --date "@$(( $(date -d "$1" "+%s") + $OFFSET ))" "+%H%M"`
	else
		DATE=`date -j -r $(( $(date -j -f "%H:%M %p" "$1" "+%s") + $OFFSET )) "+%H%M"`
	fi
	echo `echo "$DATE" | awk '{printf "%d", $1}'`
}

function get_temp_val {
	declare -i TEMP
	TEMP=1000000/$1
	echo $TEMP
}

echo `$ROOT/updateSunrise`

MIN_AFTER_SUNSET_TIL_DARK=30

DAY_TIME=`cat $ROOT/.cached_sunrise`
NIGHT_TIME=`cat $ROOT/.cached_sunset`
NOW_TIME=$(get_now_time)

declare -i DAY_VAL
declare -i NIGHT_VAL
declare -i NOW_VAL
DAY_VAL=$(get_time_val "$DAY_TIME")
NIGHT_VAL=$(get_time_val "$NIGHT_TIME" "$MIN_AFTER_SUNSET_TIL_DARK")
NOW_VAL=$(get_time_val "$NOW_TIME")
# echo SUNSET: $(get_time_val "$NIGHT_TIME")
# echo ACTUAL DARK: $(get_time_val "$NIGHT_TIME" "$MIN_AFTER_SUNSET_TIL_DARK")
function api {
	APIKEY="newdeveloper"
	HUB_IP="192.168.2.142"

	JSON=$1
	LIGHT=$2

	curl -X PUT -d"$JSON" http://$HUB_IP/api/$APIKEY/lights/$LIGHT/state
}
