#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi

LOCAL_LIGHTS="1 3"

SUNRISE_LAST_MODIFIED=`stat -c "%y" "$ROOT/.cached_sunrise" 2>/dev/null | cut -d " " -f 1`

if [ "X$SUNRISE_LAST_MODIFIED" == "X" ]; then
	SUNRISE_LAST_MODIFIED=`stat -f "%Sm" "$ROOT/.cached_sunrise" | cut -d " " -f 1-2,4`
fi

DAY_TEMP="5700"
NIGHT_TEMP="2900"

function api {
	APIKEY="newdeveloper"
	HUB_IP="192.168.2.142"

	JSON=$1
	LIGHT=$2

	curl -X PUT -d"$JSON" http://$HUB_IP/api/$APIKEY/lights/$LIGHT/state
}
