#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi
source "$ROOT/_common"

group_api '{ "bri": 0 }' 4

group_api '{ "bri": 40 }' 5 # new lights, don't make quite so dark
