#!/bin/bash

APIKEY="computer-lastclientchecker"
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi
HUB_IP="`$ROOT/_hub_IP`"

curl -X GET http://$HUB_IP/api/$APIKEY
