#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi

KEEP_WHAT_ALIVE="knob"

RUNNING=`ps ax | grep $KEEP_WHAT_ALIVE | grep -v grep | awk '{ printf $0 }'`

while [ true ]; do
	sleep 15
	if [ "X$RUNNING" == "X" ]; then
		$ROOT/restart_knob
	fi
done
