#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi

KEEP_WHAT_ALIVE="knob"

while [ true ]; do
	RUNNING=`ps ax | grep $KEEP_WHAT_ALIVE | grep -v grep | awk '{ printf $0 }'`
	if [ "X$RUNNING" == "X" ]; then
		echo "Knob service not found. Triggering restart"
		echo "PS: $RUNNING"
		$ROOT/restart_knob
	else
		echo "Knob running. Sleeping 15."
		echo "PS: $RUNNING"
	fi
	sleep 15
done
