#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi
source "$ROOT/_common"

if [ "X$1" != "X" ]; then
	LOCAL_GROUP="$1"
fi

for LIGHT in $LOCAL_GROUP
do
	group_api '{ "on": true }' $LIGHT
done

