#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi
source "$ROOT/_common"

if [ $NOW_VAL -gt $DAY_VAL -a $NOW_VAL -lt $NIGHT_VAL ]; then
	CURRENT_TEMP=$DAY_TEMP
else
	CURRENT_TEMP=$NIGHT_TEMP
fi

TEMPVAL=$(get_temp_val $CURRENT_TEMP)

for LIGHT in $LOCAL_LIGHTS
do
	api "{ \"ct\": $TEMPVAL, \"on\": true }" $LIGHT
done