#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi
source "$ROOT/_common"

for LIGHT in $LOCAL_LIGHTS
do
	api "{ \"ct\": $TEMPVAL, \"on\": true, \"bri\": $CURRENT_BRI, \"transitiontime\": 60 }" $LIGHT
done