#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi
source "$ROOT/_common"

declare -i TEMP
TEMP=1000000/$1

for LIGHT in $LOCAL_LIGHTS
do
	api "{ \"ct\": $TEMP }" $LIGHT
done