#!/bin/bash
ROOT="$(dirname $(realpath $0))"
if [ "X$ROOT" == "X" ]; then ROOT="$(dirname $0)"; fi
source "$ROOT/_common"

TEMPVAL=$(get_temp_val $1)

for LIGHT in $LOCAL_LIGHTS
do
	api "{ \"ct\": $TEMPVAL }" $LIGHT
done